spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/student_db
    username: pradeephv
    password: pradeephv  # Replace with the actual password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create  # This will create the database schema on startup
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
